### ISSUE TITLE
feat: share option to share event

### ISSUE THREAD

**Issue by Rohitha-pudu** [Tanay-ErrorCode/lupo-skill#248]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Tanay-ErrorCode** [comment]
@Rohitha-pudu Add share button **only** in the **event details page** .

![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/bc990612-2aaf-422a-a6e2-ae817e3c9122)

On clicking on the share button, a modal like the image given below should open.

![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/0429c394-1b9f-4dd6-ba9b-26c3c04168c2)

---
Additional context:

* Use bootstrap icons.
* Provide longer description of the issue so that it is easier to understand.
* If you don't understand anything in an PR, ask the mentor and **do not close** the PR like in #67 .

**Comment by Tanay-ErrorCode** [comment]
Closing as inactive.
